import {
  Building2,
  Car,
  ShoppingBag,
  Stethoscope,
  UtensilsCrossed,
  Wrench,
  Scissors,
  Dumbbell,
  Trophy,
  GraduationCap,
  PartyPopper,
  BedDouble,
  Pill,
  PawPrint,
  Scale,
  HardHat,
  Sprout,
  HeartPulse,
  CalendarClock,
  type LucideIcon,
} from "lucide-react";
import type { CategoryKey, GroupKey } from "@/lib/catalog";

export const categoryIcons: Record<CategoryKey, LucideIcon> = {
  food: UtensilsCrossed,
  retail: ShoppingBag,
  services: Wrench,
  healthcare: Stethoscope,
  realEstate: Building2,
  automotive: Car,
  beauty: Scissors,
  fitness: Dumbbell,
  sportsCourts: Trophy,
  education: GraduationCap,
  events: PartyPopper,
  hospitality: BedDouble,
  pharmacy: Pill,
  petCare: PawPrint,
  professional: Scale,
  contractors: HardHat,
  farm: Sprout,
};

// Icons for the top-level groups (navigation layer above sectors).
export const groupIcons: Record<GroupKey, LucideIcon> = {
  shopping: ShoppingBag,
  food: UtensilsCrossed,
  services: Wrench,
  health: HeartPulse,
  sports: Dumbbell,
  bookings: CalendarClock,
  realEstate: Building2,
  automotive: Car,
  education: GraduationCap,
};
